######################################################################
# Automatically generated by qmake (2.01a) niedz. sie 14 19:24:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gfx.h \
    citymap.h \
    citybuilding.h \
    cityitem.h \
    timer.h
SOURCES += gfx.cpp main.cpp \
    citymap.cpp \
    citybuilding.cpp \
    cityitem.cpp \
    timer.cpp

LIBS += -lSDL -lSDL_image
