######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 1 17:24:29 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

LIBS = -lalut
