#!/bin/bash
OUT_FILE="src.pri"

function generate_header {
cat << eom
# File automatically generated by $0. Do not edit manually.
eom
}

function generate_dirs {
dirs=`find . -mindepth 1 -type d | cut -c  3- | tr "\n" " "`
echo "DEPENDPATH += . ${dirs}"
echo "INCLUDEPATH += . ${dirs}"
echo ""
}

function generate_header_files {
files=`find . -type f -iname "*.h" -o -iname "*.hpp" | cut -c 3- | sort`
echo "HEADERS += \\"
for i in $files ; do
	echo "           $i \\"
done
echo
}

function generate_src_files {
files=`find . -type f -iname "*.c" -o -iname "*.cpp" | cut -c 3- | sort`
echo "SOURCES += \\"
for i in $files ; do
	echo "           $i \\"
done
echo
}


generate_header > $OUT_FILE
generate_dirs >> $OUT_FILE
generate_header_files >> $OUT_FILE
generate_src_files >> $OUT_FILE
